apiVersion: cactuar.rs/v1
kind: ServiceAlerts
metadata:
  name: fubar-alerter
spec:
  commonLabels:
    origin: cloud
    owner: bar
  serviceSelector:
    name: fubar-service
  alerts:
    - replicas:
        warning:
          lessThan: 3
        critical:
          lessThan: 1
    - requestErrorPercent:
        critical:
          equalTo: 100
