apiVersion: cactuar.rs/v1
kind: ServiceAlert
metadata:
  name: example-service-alert
spec:
  commonLabels:
    origin: cloud
    owner: bar
  deploymentName: best-service-eu
  alerts:
    HTTP:
      latencyMillisecondsP99:
        - operation: MoreThan
          value: 20
          for: 5m
          withLabels:
            severity: warning
        - operation: MoreThan
          value: 50
          for: 2m
          withLabels:
            severity: critical
    gRPC:
      errorPercent:
        - operation: MoreThan
          value: 10 # %
          for: 3m
          withLabels:
            severity: warning
    replica:
      count:
        - operation: LessThan
          value: 3
          for: 5m
          withLabels:
            severity: warning
        - operation: EqualTo
          value: 0
          for: 1m
          withLabels:
            severity: critical
