apiVersion: cactuar.rs/v1
kind: ServiceAlert
metadata:
  name: example-service-alert
spec:
  commonLabels:
    origin: cloud
    owner: bar
  deploymentName: best-service-eu
  alerts:
    replicaCount:
      - operation: LessThan
        value: 3
        for: 3m
        alertWithLabels:
          severity: warning
      - operation: EqualTo
        value: 0
        for: 0m
        alertWithLabels:
          severity: critical
    latencyMillisecondsP99:
      - operation: MoreThan
        value: 20
        for: 5m
        alertWithLabels:
          severity: warning
      - operation: MoreThan
        value: 50
        for: 2m
        alertWithLabels:
          severity: critical
    latencyMillisecondsP50:
      - operation: MoreThan
        value: 20
        for: 0m
        alertWithLabels:
          severity: critical
