# ================================================
# Cactuar
# ================================================
#
# Install cargo-make to run these tasks:
#   cargo install cargo-make --force
# 
# After installation, to run a task:
#   cargo make <task>

[config]
default_to_workspace = false
skip_core_tasks = true

[env]
CACTUAR_DOCKER_TARGET = "cactuar"

[tasks.test]
command = "cargo"
args = [ "nextest", "run" ]
install_crate = "cargo-nextest"

[tasks.coverage]
command = "cargo"
args = [ "llvm-cov" ]
install_crate = "cargo-llvm-cov"

[tasks.docs]
command = "cargo"
args = ["doc"]

[tasks.lint]
command = "cargo"
args = ["clippy"]

[tasks.docker]
command = "docker"
args = [
    "build",
    "--tag", # tag and target are currently the same
    "${CACTUAR_DOCKER_TARGET}:${CARGO_MAKE_GIT_HEAD_LAST_COMMIT_HASH_PREFIX}",
    "--target",
    "${CACTUAR_DOCKER_TARGET}",
    ".", # build context
]
