apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cactuar
rules:
- apiGroups:
  - cactuar.rs
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
