apiVersion: v1
kind: Service
metadata:
  name: cactuar
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: cactuar
    app.kubernetes.io/name: cactuar
