apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cactuar
rules:
  - apiGroups:
    - cactuar.rs
    resources:
    - servicealerts
    verbs:
      - "*"
{{/*    - get*/}}
{{/*    - list*/}}
{{/*    - watch*/}}
{{/*    - patch*/}}

  - apiGroups:
    - cactuar.rs
    resources:
    - servicealerts/status
    verbs:
      - "*"
{{/*    - get*/}}
{{/*    - patch*/}}
{{/*    - update*/}}

  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    # TODO: this is too permissive but I was having a bad time
    - "*"
{{/*    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]*/}}
