name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  is-crd-up-to-date:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generate CRD
      run: ls -l
    - name: Check if up-to-date
      run: |
        if [ -z "$(git status --porcelain)" ]; then \
          echo "Generated code is up-to-date!"; \
        else \
          echo "You forgot to generate something..." \
          echo "Here's the diff:" \
          git diff \
          exit 1 \
        fi
